// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Book struct {
	BookID      int32
	UserID      int32
	Title       string
	Author      string
	Genre       string
	Condition   string
	Description pgtype.Text
	ImageUrl    pgtype.Text
	CreatedAt   pgtype.Timestamptz
}

type Review struct {
	ReviewID       int32
	ReviewedUserID int32
	ReviewerID     int32
	Rating         int32
	ReviewText     pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type SwapRequest struct {
	SwapRequestID int32
	RequesterID   int32
	BookID        int32
	Status        string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	UserID            int32
	Username          string
	Email             string
	Password          string
	ProfilePictureUrl pgtype.Text
	Bio               pgtype.Text
	Location          pgtype.Text
	CreatedAt         pgtype.Timestamptz
}
